# @package _global_

defaults:
  - trainer: inference.yaml

  # override config either in this file or using experiment config
  - _self_
  - experiment: null # experiment configs allow for version control of specific hyperparameters


# Trainer
seed: 1
batch_size: 120
n_gpus: 1

# Data
input_data: null
backward_predictions: null
dataset_type: synthesis
dataset_part: test # Which dataset split to run inference on. ["full", "train", "val", "test"]
vocabulary_path: bart_vocab_downstream.json
working_directory: .

# Output files
output_score_data: null
output_sampled_smiles: null

# Model args
model_path: null

# Fixed arguments for round-trip inference (do not change)
data_path: null # Placeholder argument
task: "forward_prediction"

callbacks:
  - ScoreCallback

scorers:
  - FractionInvalidScore
  - FractionUniqueScore
  - TanimotoSimilarityScore:
    - statistics: mean
  - TopKAccuracyScore