# @package _global_

defaults:
  - plugins: null
  - trainer: inference.yaml

  # override config either in this file or using experiment config
  - _self_
  - experiment: null # experiment configs allow for version control of specific hyperparameters


# Trainer
seed: 1
batch_size: 128
n_gpus: 1
n_chunks: 1
i_chunk: 0

# Data
data_path: null
dataset_part: test # Which dataset split to run inference on. [full", "train", "val", "test"]
dataset_type: synthesis
vocabulary_path: null
task: "forward_prediction" # ["forward_prediction", "backward_prediction"]

# Output files
output_score_data: null
output_sampled_smiles: null

# Model args
model_path: null
model_type: bart            # ["bart", "unified"]
n_beams: 10
n_unique_beams: null

callbacks:
  - ScoreCallback

scorers:
  - FractionInvalidScore
  - FractionUniqueScore
  - TanimotoSimilarityScore:
    - statistics: mean
  - TopKAccuracyScore