# @package _global_

defaults:
  # override config either in this file or using experiment config
  - _self_
  - experiment: null # experiment configs allow for version control of specific hyperparameters


# Setting
batch_size: 64
n_beams: 10
n_gpus: 1

# Data
reactants_path: null
products_path: null
vocabulary_path: vocab/bart_vocab.json"
task: forward_prediction    # ["forward_prediction", "backward_prediction", "mol_opt"]


# Model
model_path: null
model_type: bart            # ["bart", "unified"]
dataset_part: full      # ["full", "train", "val", "test"]
